name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Ensure test directories exist
        run: mkdir -p tests/out tests/data

      - name: Cache test feature stack
        id: cache-feature-stack
        uses: actions/cache@v4
        with:
          path: tests/data
          key: feature-stack-tif-v1

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-path: pyproject.toml

      # TODO: add linting in here w/ ruff?

      - name: Install dependencies with extras [cpu,dev]
        run: uv sync --extra cpu --extra dev

      - name: Download feature stack (if cache miss)
        if: steps.cache-feature-stack.outputs.cache-hit != 'true'
        run: curl -L -o tests/data/feature-stack.tif https://sambasegment.blob.core.windows.net/resources/isb_test_data/feature-stack.tif

      - name: Run tests
        run: uv run pytest -s
