name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          # Adjust if you use a different dependency file
          cache-dependency-path: |
            pyproject.toml
            uv.lock

      - name: Install dependencies with extras [cpu,dev]
        run: uv sync --extra cpu --extra dev

      - name: Prepare test data
        run: |
          mkdir -p tests/out
          curl -o tests/data/feature-stack.tif https://sambasegment.blob.core.windows.net/resources/isb_test_data/feature-stack.tif

      - name: Run tests
        run: uv run pytest -s
